files:
  - source: /lang/en_us.json
    translation: /lang/%locale_with_underscore%.%file_extension%
    escape_quotes: 0
    languages_mapping:
      locale_with_underscore:
        ach_UG: ach_ug
        aa_ER: aa_er
        af_ZA: af_za
        ak_GH: ak_gh
        tw_TW: tw_tw
        sq_AL: sq_al
        am_ET: am_et
        ar_BH: ar_bh
        ar_EG: ar_eg
        ar_SA: ar_sa
        ar_YE: ar_ye
        an_ES: an_es
        hy_AM: hy_am
        frp_IT: frp_it
        as_IN: as_in
        ast_ES: ast_es
        tay_TW: tay_tw
        av_DA: av_da
        ae_IR: ae_ir
        ay_BO: ay_bo
        az_AZ: az_az
        ban_ID: ban_id
        bal_BA: bal_ba
        bm_ML: bm_ml
        ba_RU: ba_ru
        eu_ES: eu_es
        be_BY: be_by
        bn_BD: bn_bd
        bn_IN: bn_in
        ber_DZ: ber_dz
        bh_IN: bh_in
        bfo_BF: bfo_bf
        bi_VU: bi_vu
        bs_BA: bs_ba
        br_FR: br_fr
        bg_BG: bg_bg
        my_MM: my_mm
        ca_ES: ca_es
        ceb_PH: ceb_ph
        ch_GU: ch_gu
        ce_CE: ce_ce
        chr_US: chr_us
        ny_MW: ny_mw
        zh_CN: zh_cn
        zh_SG: zh_sg
        zh_TW: zh_tw
        zh_HK: zh_hk
        zh_MO: zh_mo
        cv_CU: cv_cu
        kw_GB: kw_gb
        co_FR: co_fr
        cr_NT: cr_nt
        hr_HR: hr_hr
        cs_CZ: cs_cz
        da_DK: da_dk
        fa_AF: fa_af
        dv_MV: dv_mv
        nl_NL: nl_nl
        nl_BE: nl_be
        nl_SR: nl_sr
        dz_BT: dz_bt
        en_US: en_us
        en_AR: en_ar
        en_AU: en_au
        en_BZ: en_bz
        en_CA: en_ca
        en_CB: en_cb
        en_CN: en_cn
        en_DK: en_dk
        en_HK: en_hk
        en_IN: en_in
        en_ID: en_id
        en_IE: en_ie
        en_JM: en_jm
        en_JA: en_ja
        en_MY: en_my
        en_NZ: en_nz
        en_NO: en_no
        en_PH: en_ph
        en_PR: en_pr
        en_SG: en_sg
        en_ZA: en_za
        en_SE: en_se
        en_GB: en_gb
        en_ZW: en_zw
        eo_UY: eo_uy
        et_EE: et_ee
        ee_GH: ee_gh
        fo_FO: fo_fo
        fj_FJ: fj_fj
        fil_PH: fil_ph
        fi_FI: fi_fi
        vls_BE: vls_be
        fra_DE: fra_de
        fr_FR: fr_fr
        fr_BE: fr_be
        fr_CA: fr_ca
        fr_LU: fr_lu
        fr_QC: fr_qc
        fr_CH: fr_ch
        fy_NL: fy_nl
        fur_IT: fur_it
        ff_ZA: ff_za
        gaa_GH: gaa_gh
        gl_ES: gl_es
        ka_GE: ka_ge
        de_DE: de_de
        de_AT: de_at
        de_BE: de_be
        de_LI: de_li
        de_LU: de_lu
        de_CH: de_ch
        el_GR: el_gr
        el_CY: el_cy
        kl_GL: kl_gl
        gn_PY: gn_py
        gu_IN: gu_in
        ht_HT: ht_ht
        ha_HG: ha_hg
        haw_US: haw_us
        he_IL: he_il
        hz_NA: hz_na
        hil_PH: hil_ph
        hi_IN: hi_in
        ho_PG: ho_pg
        hmn_CN: hmn_cn
        hu_HU: hu_hu
        is_IS: is_is
        io_EN: io_en
        ig_NG: ig_ng
        ilo_PH: ilo_ph
        id_ID: id_id
        iu_NU: iu_nu
        ga_IE: ga_ie
        it_IT: it_it
        it_CH: it_ch
        ja_JP: ja_jp
        jv_ID: jv_id
        quc_GT: quc_gt
        kab_KAB: kab_kab
        kn_IN: kn_in
        pam_PH: pam_ph
        ks_IN: ks_in
        ks_PK: ks_pk
        csb_PL: csb_pl
        kk_KZ: kk_kz
        km_KH: km_kh
        rw_RW: rw_rw
        kv_KO: kv_ko
        kg_CG: kg_cg
        kok_IN: kok_in
        ko_KR: ko_kr
        ku_TR: ku_tr
        kmr_TR: kmr_tr
        kj_AO: kj_ao
        ky_KG: ky_kg
        lo_LA: lo_la
        la_LA: la_la
        lv_LV: lv_lv
        lij_IT: lij_it
        li_LI: li_li
        ln_CD: ln_cd
        lt_LT: lt_lt
        nds_DE: nds_de
        dsb_DE: dsb_de
        lg_UG: lg_ug
        luy_KE: luy_ke
        lb_LU: lb_lu
        mk_MK: mk_mk
        mai_IN: mai_in
        mg_MG: mg_mg
        ms_MY: ms_my
        ms_BN: ms_bn
        ml_IN: ml_in
        mt_MT: mt_mt
        mi_NZ: mi_nz
        arn_CL: arn_cl
        mr_IN: mr_in
        mh_MH: mh_mh
        mn_MN: mn_mn
        mos_MOS: mos_mos
        na_NR: na_nr
        ng_NA: ng_na
        ne_NP: ne_np
        ne_IN: ne_in
        pcm_NG: pcm_ng
        se_NO: se_no
        ns_ZA: ns_za
        no_NO: no_no
        nb_NO: nb_no
        nn_NO: nn_no
        oc_FR: oc_fr
        or_IN: or_in
        oj_CA: oj_ca
        om_ET: om_et
        os_SE: os_se
        pi_IN: pi_in
        pap_PAP: pap_pap
        ps_AF: ps_af
        fa_IR: fa_ir
        pl_PL: pl_pl
        pt_PT: pt_pt
        pt_BR: pt_br
        pa_IN: pa_in
        pa_PK: pa_pk
        qu_PE: qu_pe
        ro_RO: ro_ro
        rm_CH: rm_ch
        rn_BI: rn_bi
        ru_RU: ru_ru
        ru_BY: ru_by
        ru_MD: ru_md
        sah_SAH: sah_sah
        sg_CF: sg_cf
        sa_IN: sa_in
        sat_IN: sat_in
        sc_IT: sc_it
        sco_GB: sco_gb
        gd_GB: gd_gb
        srp: srp
        sr_Cyrl: sr_cyrl
        sr_Latn: sr_latn
        sh_HR: sh_hr
        crs_SC: crs_sc
        sn_ZW: sn_zw
        ii_CN: ii_cn
        sd_PK: sd_pk
        si_LK: si_lk
        sk_SK: sk_sk
        sl_SI: sl_si
        so_SO: so_so
        son_ZA: son_za
        ckb_IR: ckb_ir
        nr_ZA: nr_za
        sma_NO: sma_no
        st_ZA: st_za
        es_ES: es_es
        es_EM: es_em
        es_AR: es_ar
        es_BO: es_bo
        es_CL: es_cl
        es_CO: es_co
        es_CR: es_cr
        es_DO: es_do
        es_EC: es_ec
        es_SV: es_sv
        es_GT: es_gt
        es_HN: es_hn
        es_419: es_419
        es_MX: es_mx
        es_NI: es_ni
        es_PA: es_pa
        es_PY: es_py
        es_PE: es_pe
        es_PR: es_pr
        es_US: es_us
        es_UY: es_uy
        es_VE: es_ve
        su_ID: su_id
        sw_KE: sw_ke
        sw_TZ: sw_tz
        ss_ZA: ss_za
        sv_SE: sv_se
        sv_FI: sv_fi
        syc_SY: syc_sy
        tl_PH: tl_ph
        ty_PF: ty_pf
        tg_TJ: tg_tj
        ta_IN: ta_in
        tt_RU: tt_ru
        te_IN: te_in
        kdh_KDH: kdh_kdh
        th_TH: th_th
        bo_BT: bo_bt
        ti_ER: ti_er
        ts_ZA: ts_za
        tn_ZA: tn_za
        tr_TR: tr_tr
        tr_CY: tr_cy
        tk_TM: tk_tm
        uk_UA: uk_ua
        hsb_DE: hsb_de
        ur_IN: ur_in
        ur_PK: ur_pk
        ug_CN: ug_cn
        uz_UZ: uz_uz
        val_ES: val_es
        ve_ZA: ve_za
        vec_IT: vec_it
        vi_VN: vi_vn
        wa_BE: wa_be
        cy_GB: cy_gb
        wo_SN: wo_sn
        xh_ZA: xh_za
        yi_DE: yi_de
        yo_NG: yo_ng
        zea_ZEA: zea_zea
        zu_ZA: zu_za
